#!/usr/bin/env python

import pyautogui
from collections import namedtuple

GameConfig = namedtuple("GameConfig", [
    "id", "slot_size", "spin_btn", "auto_spin", "turbo", "feature",
    "auto_play_menu", "widescreen", "provider"
])

GAME_CONFIGS = {
    # Jili
    "10 Sparkling Crown": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Charge Buffalo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Coin Treasures": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Coin Treasures 2": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Coin Wild Horse": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 LUCKY LION": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Lucky Piggy": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Pot Dragons": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "3 Witch's Lamp": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "40 Sparkling Crown": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "7up7down": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Agent Ace": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Ali Baba": GameConfig(6566, "small", False, True, True, None, False, True, "JILI"),
    "Arena Fighter": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Aztec Priestess": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Baccarat": GameConfig(6595, None, False, True, True, None, False, True, "JILI"),
    "Bangla Beauty": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Bao boon chin": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Big Small": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Bikini Lady": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Bingo Adventure": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Bingo Carnaval": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Bone Fortune": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Bonus Hunter": GameConfig(0, "small", False, True, True, None, False, False, "JILI"),
    "Book of Gold": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Boxing Extravaganza": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Boxing King": GameConfig(6553, "small", False, True, True, None, False, True, "JILI"),
    "Bubble Beauty": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Calaca Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Candy Baby": GameConfig(6543, "small", False, True, True, None, False, False, "JILI"),
    "Charge Buffalo": GameConfig(6548, "small", False, True, True, None, False, True, "JILI"),
    "Charge Buffalo Ascent": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Chin Shi Huang": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Circus Joker 4096": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Clover Coins 3x3": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Coin Infinity Surge Reel": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Coin Tree": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crash Bonus": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crash Cricket": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crash Goal": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crash Touchdown": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crazy FaFaFa": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crazy Hunter": GameConfig(6561, "small", False, True, True, None, False, True, "JILI"),
    "Crazy Hunter 2": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crazy Pusher": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Crazy777": GameConfig(6537, "small", False, True, True, None, False, True, "JILI"),
    "Cricket King 18": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Cricket Sah 75": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Dabanggg": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Devil Fire": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Devil Fire 2": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Diamond Party": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "DiamondParty": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Dragon Treasure": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Egypt's Glow": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Elf Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "European Roulette": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fa Fa Fa": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fengshen": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fish Prawn Crab": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Coins": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems": GameConfig(6560, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems 2": GameConfig(6622, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems 3": GameConfig(6630, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems Scratch": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Monkey": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Pig": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fortune Tree": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "FortunePig": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Fruity Wheel": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Gem Party": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Go For Champion": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Go Goal Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "God Of Martial": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Gold Rush": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Golden Bank": GameConfig(6545, "small", False, True, True, None, False, True, "JILI"),
    "Golden Bank 2": GameConfig(6635, "small", False, True, True, None, False, True, "JILI"),
    "Golden Empire": GameConfig(6559, "small", False, True, True, None, False, True, "JILI"),
    "Golden Empire 2": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Golden Joker": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Golden Land": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Golden Queen": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Golden Temple": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Golden Treasure Lightning": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Happy Taxi": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Hawaii Beauty": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Hilo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Hot Chilli": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Hyper Burst": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Jili Caishen": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Jackpot Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Jackpot Joker": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Jhandi Munda": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Jogo Do Bicho": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Joker Coins": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Journey West M": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Jungle King": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Keno": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Keno Bonus Number": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Keno Super Chance": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "King Arthur": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Legacy of Egypt": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Lucky Ball": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Lucky Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Lucky Coming": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Lucky Doggy": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Lucky Goldbricks": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Lucky Jaguar": GameConfig(6636, "small", False, True, True, None, False, True, "JILI"),
    "Magic Lamp": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Magic Lamp Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Master Tiger": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Mayan Empire": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    # "Medusa": GameConfig(0, "small", False, True, True, None, False, True, "JILI"), Conflict Key same name
    "Mega Ace": GameConfig(6567, "small", False, True, True, None, False, False, "JILI"),
    "Mines Gold": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Mines Grand": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Money Coming": GameConfig(6551, "small", False, True, True, None, False, True, "JILI"),
    "Money Coming 2": GameConfig(9474, "small", False, True, True, None, False, True, "JILI"),
    "Money Coming Expand Bets": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Money Pot": GameConfig(6637, "small", False, True, True, None, False, True, "JILI"),
    "Money Pot Deluxe": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Monkey Party": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Neko Fortune": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Night City": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Nightfall Hunting": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Number King": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Pappu": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Party Ape": GameConfig(0, "small", False, True, True, None, False, False, "JILI"),
    "Party Night": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Party Star": GameConfig(0, "small", False, True, True, None, False, False, "JILI"),
    "Pharaoh Treasure": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Pirate Queen": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Pirate Queen 2": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Plinko": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Poker King": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Poseidon": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Potion Wizard": GameConfig(6632, "small", False, True, True, None, False, True, "JILI"),
    "Roma X Deluxe": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "RomaX": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Safari King": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Safari Mystery": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Samba": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Secret Treasure": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Seven Seven Seven": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "SevenSevenSeven": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Shanghai Beauty": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Shōgun": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Sic Bo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Sin City": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Speed Baccarat": GameConfig(0, None, False, True, True, None, False, True, "JILI"),
    "Super Ace": GameConfig(6549, "small", False, True, True, None, False, False, "JILI"),
    "Super Ace Deluxe": GameConfig(6626, "small", False, True, True, None, False, False, "JILI"),
    "Super Ace II": GameConfig(9475, "small", False, True, True, None, False, False, "JILI"),
    "Super Ace Joker": GameConfig(6629, "small", False, True, True, None, False, False, "JILI"),
    "Super Ace Scratch": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Super Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Super E-Sabong": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Super Rich": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Sweet Land": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Twin Wins": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "The Pig House": GameConfig(6633, "small", False, True, True, None, False, True, "JILI"),
    "Thor X": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Treasure Quest": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Trial of Phoenix": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Video Poker": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "War Of Dragons": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "West Hunger Bingo": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Wheel": GameConfig(6628, "small", False, True, True, None, False, True, "JILI"),
    "Wild Ace": GameConfig(0, "small", False, True, True, None, False, False, "JILI"),
    "Wild Racer": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Win Drop": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Witches Night": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "World Cup": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Xi Yang Yang": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "XiYangYang": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    "Zeus": GameConfig(0, "small", False, True, True, None, False, True, "JILI"),
    # Pocket Game Soft
    "Alchemy Gold": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Anubis Wrath": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Asgardian Rising": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Bakery Bonanza": GameConfig(9539, "small", False, True, True, None, False, False, "PG"),
    "Bali Vacation": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Battleground Royale": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Bikini Paradise": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Buffalo Win": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Butterfly Blossom": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Caishen Wins": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Candy Bonanza": GameConfig(9546, "small", False, True, True, None, False, False, "PG"),
    "Candy Burst": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Captain's Bounty": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Cash Mania": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Chicky Run": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Chocolate Deluxe": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Circus Delight": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Cocktail Nights": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Cruise Royale": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Crypto Gold": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Dead Man's Riches": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Destiny of Sun & Moon": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Diner Delights": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Diner Frenzy Spins": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Doomsday Rampage": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Double Fortune": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Dragon Hatch": GameConfig(9555, "small", False, True, True, None, False, False, "PG"),
    "Dragon Hatch 2": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Dragon Legend": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Dragon Tiger Luck": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Dragon's Treasure Quest": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Dreams of Macau": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Egypt's Book of Mystery": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Emoji Riches": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Emperor's Favour": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Flirting Scholar": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Forge of Wealth": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Dragon": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Gods": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Mouse": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Ox": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Rabbit": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Snake": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fortune Tiger": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fruit Candy": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Fruity Candy": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Futebol Fever": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Galactic Gems": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Galaxy Miner": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ganesha Fortune": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ganesha Gold": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Garuda Gems": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Geisha's Revenge": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Gem Saviour": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Gem Saviour Conquest": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Gem Saviour Sword": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Gemstones Gold": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Genie's 3 Wishes": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Gladiator's Glory": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Graffiti Rush": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Grimms' Bounty: Hansel & Gretel": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Guardians of Ice and Fire": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Hawaiian Tiki": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Heist Stakes": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Heist of Stakes": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Hip Hop Panda": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Honey Trap of Diao Chan": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Hood vs Wolf": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Hotpot": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Incan Wonders": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Jack Frost's Winter": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Jack the Giant Hunter": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Jewels of Prosperity": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Journey to the Wealth": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Jungle Delight": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Jurassic Kingdom": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Knockout Riches": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Legend of Hou Yi": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Legend of Perseus": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Legendary Monkey King": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Leprechaun Riches": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Lucky Clover Lady": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Lucky Clover Riches": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Lucky Neko": GameConfig(9591, "small", False, True, True, None, False, False, "PG"),
    "Lucky Piggy": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mafia Mayhem": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mahjong Ways": GameConfig(9593, "small", False, True, True, None, False, False, "PG"),
    "Mahjong Ways 2": GameConfig(9594, "small", False, True, True, None, False, False, "PG"),
    "Majestic Treasures": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mask Carnival": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Medusa": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Medusa II": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mermaid Riches": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Midas Fortune": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mr. Hallow-Win": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mr. Treasure’s Fortune": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Muay Thai Champion": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Museum Mystery": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mystic Potion": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Mystical Spirits": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ninja Raccoon Frenzy": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ninja Racoon Frenzy": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ninja vs Samurai": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Oishi Delights": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Opera Dynasty": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Oriental Prosperity": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Phoenix Rises": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Piggy Gold": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Pinata Wins": GameConfig(10776, "small", False, True, True, None, False, False, "PG"),
    "Plushie Frenzy": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Prosperity Fortune Tree": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Prosperity Lion": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Queen of Bounty": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Raider Jane's Crypt of Fortune": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Rave Party Fever": GameConfig(9613, "small", False, True, True, None, False, False, "PG"),
    "Reel Love": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Rio Fantasia": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Rise of Apollo": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Rooster Rumble": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Safari Wilds": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Santa's Gift Rush": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Secret of Cleopatra": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Secrets of Cleopatra": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Shaolin Soccer": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Shark Bounty": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Songkran Splash": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Speed Winner": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Spirited Wonders": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Super Golf Drive": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Supermarket Spree": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Symbols of Egypt": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Thai River Wonders": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "The Great Icescape": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "The Queen's Banquet": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Three Crazy Piggies": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Totem Wonders": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Treasures of Aztec": GameConfig(9628, "small", False, True, True, None, False, False, "PG"),
    "Tree of Fortune": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Tsar Treasures": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ultimate Striker": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Vampire's Charm": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ways of Qilin": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Ways of the Qilin": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Werewolf's Hunt": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wild Ape #3258": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wild Ape#3258": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wild Bandito": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wild Bounty Showdown": GameConfig(9633, "small", False, True, True, None, False, False, "PG"),
    "Wild Coaster": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wild Fireworks": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wild Heist Cashout": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Win Win Fish Prawn Crab": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Win Win Won": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Wings of Iguazu": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Yakuza Honor": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    "Zombie Outbreak": GameConfig(0, "small", False, True, True, None, False, False, "PG"),
    # Fa Chai
    "Animal Racing": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Boxing Riches": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Chilihuahua": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Chinese New Year": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Chinese New Year 2": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Cowboys": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Crazy Buffalo": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Chinese New Year Moreways": GameConfig(10964, "small", True, True, True, None, False, False, "FC"),
    "Circus Dozer": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Da Le Men": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Egypt Bonanza": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Fortune Egg": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Fortune Koi": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Fortune Sheep": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Fa Chai Dozer": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Fortune Goddess": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Fortune Money Boom": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Glory of Rome": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Gold Rush": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Golden Genie": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Golden Panther": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Grand Blue": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Go Go Rise": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Gods Grant Fortune": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Happy Duo Bao": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Hot Pot Party": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Jungle Bang Bang": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Legend of Inca": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Lucky Fortunes": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Lucky Fortunes 3x3": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Luxury The Golden Panther": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Lightning Bomb": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Luxury Golden Panther": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Magic Beans": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Merge Magic": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Mines": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Money Tree Dozer": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Night Market": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Night Market 2": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Panda Dragon Boat": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Phoenix Fever": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Pong Pong Hu": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Poker Win": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Queen of Inca": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Rich Man": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Robin Hood": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Roma Gladiatrix": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang": GameConfig(6667, "small", True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang 2": GameConfig(6686, "small", True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang Plus": GameConfig(10966, "small", True, True, True, None, False, False, "FC"),
    "Super Color Game": GameConfig(6677, "small", True, True, True, None, False, False, "FC"),
    "Super Elements": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "The The Golden Panther": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Three Little Pigs": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Treasure Cruise": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Treasure Raiders": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Treasures of Odin": GameConfig(10880, "small", True, True, True, None, False, False, "FC"),
    "Tower": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "War of the Universe": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Win Win Neko": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    "Zeus": GameConfig(0, "small", True, True, True, None, False, False, "FC"),
    # JDB
    "Aviator Extra Bet": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Banana Saga": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Beer Tycoon": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Big Three Dragons": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Birds and Animals": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Birds Party Deluxe": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Boom Fiesta": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Bull Treasure": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Cai Shen Bingo": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Cai Shen Party": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Caishen Coming": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Chef Panda": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Classic Mario": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Coo Coo Farm": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Crazy King Kong": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Dice": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Double Wilds": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Dragon Soar - Hyper Wild": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Dragon Warrior": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Dragon's Gate": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Egypt Treasure": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Firework Burst": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Fishin' Fever X-Huge": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Flirting Scholar Tang II": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Fortune Horse": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Fortune Jewel": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Fortune Neko": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Fortune Treasure": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Fruity Bonanza Combo": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Funky King Kong": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Galaxy Burst": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Glamorous Girl": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Go Lai Fu": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Goal": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Golden Disco": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Guan Gong": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Happy New Year": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "HiLo": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Horse Racing": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Huaguoshan Legends": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Jogo Do Bicho": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Jungle Jungle": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "King of Football": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Koi Trio": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lantern Wealth": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Legendary 5": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Llama Adventure": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lucky Color Game": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lucky Diamond": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lucky Dragon": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lucky Dragons": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lucky Qilin": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Lucky Racing": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Magic Ace Wild Lock": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Mahjong": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Maya Gold Crazy": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Miner Babe": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Mines": GameConfig(6609, "small", False, True, True, True, True, True, "JDB"),
    "Mines 2": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Mining Upstart": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Mjolnir": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Mole Crash": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Moneybags Man": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Napoleon": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Olympig": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "One Punch Man": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Orient Animals": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Panda Panda": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Pirate Treasure": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Plinko": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Pop Pop Candy 1000": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Prosperity Tiger": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Ragnarok: Thor vs Loki": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Rocket Derby": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Rolling in Money": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Rooster in Love": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Spindrift": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Spindrift 2": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Super Niubi Deluxe": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Super Super Fruit": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "The Llama Adventure": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Triple King Kong": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Wealthway": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Winning Mask": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Wonder Elephant": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    "Xi Yang Yang": GameConfig(0, "small", False, True, True, True, True, True, "JDB"),
    # Pragmatic Play
    "3 Buzzing Wilds": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "3 Dancing Monkeys": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "3 Dancing Monkeys™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "5 Frozen Charms Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "5 Lions Dance": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "5 Rabbits Megaways™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "6 Jokers": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "7 Clovers of Fortune": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "7 Piggies": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "8 Golden Dragon Challenge": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "888 Bonanza™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "888 Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "African Elephant": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aladdin and the Sorcerer": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Angel vs Sinner": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Anime Mecha Megaways™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aztec Blaze™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aztec Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aztec Gems": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aztec Gems Deluxe": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aztec Powernudge": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Aztec Treasure Hunt": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Badge Blitz": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bali Dragon": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bandit Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Barn Festival": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Barnyard Megahays Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Beware The Deep Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Amazon Xtreme": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza - Keeping It Reel": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza - Reel Action": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Christmas Bash": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Christmas Bash™ (Reel Kingdom Game)": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Crash": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Day at the Races": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Floats My Boat": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Halloween": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Hold & Spinner": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Hold & Spinner Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Mission Fishin'": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Secrets of the Golden Lake": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Splash": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Vegas Double Down Deluxe": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Bass Xmas Xtreme": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Big Juan": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bigger Bass Blizzard - Christmas Catch": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bigger Bass Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Black Bull": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Blade & Fangs": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Blazing Wilds Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bomb Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Book of Golden Sands": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Book of Tut Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bounty Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Bow of Artemis": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Buffalo King": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Buffalo King Untamed Megaways™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Caishen's Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Candy Blitz Bombs": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Candy Corner": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Candy Jar Cluster": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Candy Jar Clusters": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Candy Stars": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cash Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cash Box": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cash Box™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cash Chips": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cash Elevator": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Casino Heist Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Castle of Fire": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Chase for Glory": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cheeky Emperor™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Chests of Cai Shen": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Chicken Chase – Caccia alla Gallina": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Chicken Drop": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Chilli Heat Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Christmas Big Bass Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Christmas Carol Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cleocatra": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Clover Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Club Tropicana": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Coffee Wild™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Colossal Cash Zone": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Congo Cash": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Congo Cash XL": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cosmic Cash": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cowboy Coins": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cowboys Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Crank it Up": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Crown of Fire": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Crystal Caverns Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Curse of the Werewolf Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cyber Heist": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Cyclops Smash": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dance Party": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Day of Dead": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Demon Pots": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Demon Pots™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Devilicious": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Diamond Cascade": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Diamond Strike": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Diamonds of Egypt": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Ding Dong Christmas Bells": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Down the Rails": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dragon Gold 88": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dragon Hero": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dragon Hero™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dragon Hot Hold and Spin": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dragon Kingdom - Eyes of Fire": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dwarf & Dragon": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Dynamite Diggin Doug": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Egyptian Fortunes": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Elemental Gems Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Emerald King Rainbow Road": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Empty the Bank": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Excalibur Unleashed": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Extra Juicy Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Eye of Cleopatra": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Eye of the Storm": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fairytale Fortune": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fat Panda": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fiery Wild Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Archer": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Hot 100": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Hot 20": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Hot 40": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Hot 5": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Portals": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Strike": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fire Strike 2": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Firebird Spirit": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fish Eye": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fishin' Reels": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Floating Dragon": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Floating Dragon - Dragon Boat Festival": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Floating Dragon Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Floating Dragon New Year Festival Ultra Megaways Hold & Spin": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fortune Ace": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fortune Dragon": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fortune Hit'n Roll": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fortunes of Aztec": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Frogs & Bugs": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Frozen Tropics": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fruit Party": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fruit Party 2": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fruit Rainbow": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fruits of the Amazon": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fruity Treats": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Fury of Odin Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gates of Gatot Kaca": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gates of Hades": GameConfig(9534, "small", False, True, True, True, True, True, "PP"),
    "Gates of Olympus": GameConfig(9481, "small", False, True, True, True, True, True, "PP"),
    "Gates of Olympus 1000": GameConfig(9524, "small", False, True, True, True, True, True, "PP"),
    "Gates of Olympus Super Scatter": GameConfig(9535, "small", False, True, True, True, True, True, "PP"),
    "Gates of Olympus Xmas 1000": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gems Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Genie 3 Wishes": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Genie Mega Reels": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Ghostbusters": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gladiator Legends": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Goblin Heist Powernudge": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gold Party": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gold Rush": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Gold Train": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Golden Dragon Inferno": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Golden Pig": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Golden Piggy Bank": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Golden Tiger": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Greek Gods": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Greedy Wolf": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Green Chilli": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Grizzly Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Guardians of The Monastery": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Guardians of the Void": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Himalayan Wild": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hercules & Pegasus": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Heroes Hunt": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot Fiesta": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot Pepper": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot Safari": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot to Burn": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot to Burn Extreme": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot to Burn Hold & Spin": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot to Burn Jackpot": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Hot Triple Sevens": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Irish Charms": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Irish Clover": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Irish Clover 100": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Irish Pot Luck": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Jasmine Dreams": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Joker King": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Jokers Jewels": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Aztec Treasure": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Book of Tut": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Book of Tut Respin": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Mayan Gods": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Quest for Bermuda Riches": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Tomb of the Scarab Queen": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Joker’s Coins Hold & Win": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Kingdom of The Dead": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Knight Hot Spotz": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Kraken's Sky Bounty": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Legend of Heroes Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Legend of The Golden Monkey": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Little Gem": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Little Gem Hold & Spin": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Loch Ness Loot": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Lucky Dragons": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Lucky Grace and Charm": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Lucky Lightning": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Lucky, Grace & Charm Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Magic Journey": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mahjong Wins": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mahjong Wins 2": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Master Chen's Fortune": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Medusa Strike": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mega Don": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mega Wheel": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "MegaWheel™": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mighty Kong": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mochimon": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Monster Superlanche": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Monkey Warrior": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Money Stacks": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mummyland Treasures": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mystery of the Orient": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Mystic Chief": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Nile Fortune": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "North Guardians": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Octobeer Fortunes": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Old Gold Miner Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Oodles of Noodles": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Panda Fortune 2": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Peak Power": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Penguins Christmas Party Time": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Phoenix Forge": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Piggy Bank Bills": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Piggy Bankers": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pinup Girls": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pirate Gold Deluxe": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pirate Golden Age": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pirates Pub": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pixie Wings": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pompeii Megareels Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pot of Fortune": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Power of Merlin Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Power of Ninja": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pub Kings": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pyramid Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Pyramid King": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Queen of Gods": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Queenie": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rabbit Garden": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rainbow Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rainbow Reels": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Reel Banks": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Release the Bison": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Release the Kraken": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Release the Kraken 2": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Release the Kraken Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Revenge of Loki Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Ripe Rewards": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rise of Giza Powernudge": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rise of Samurai 4": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Robber Strike": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rocket Blast Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Rujak Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Running Sushi": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Saiyan Mania": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Samurai Code": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Santa": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Santa's Great Gifts": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Santa's Wonderland": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Santa’s Xmas Rush": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Sea Fantasy": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Secret City Gold": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Shield of Sparta": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Shining Hot 100": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Shining Hot 20": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Shining Hot 40": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Shining Hot 5": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Sky Bounty": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Smugglers Cove": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Snakes & Ladders - Snake Eyes": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Snakes and Ladders Megadice": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Spaceman": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Spartan King": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Spellbinding Mystery": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Spin & Score Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Spirit of Adventure": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Star Bounty": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Star Pirates Code": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Starlight Christmas": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Starlight Princess 1000": GameConfig(9503, "small", False, True, True, True, True, True, "PP"),
    "Starlight Princess Pachi": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Starz Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Sticky Bees": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Strawberry Cocktail": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Street Racer": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Striking Hot 5": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Sugar Rush": GameConfig(9483, "small", False, True, True, True, True, True, "PP"),
    "Sugar Rush 1000": GameConfig(9525, "small", False, True, True, True, True, True, "PP"),
    "Sumo Supreme Megaways": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Super Joker": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Super X": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Supermania": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Sweet Bonanza 1000": GameConfig(9482, "small", False, True, True, True, True, True, "PP"),
    "Sweet Bonanza 1000": GameConfig(9523, "small", False, True, True, True, True, True, "PP"),
    "Sweet Bonanza Xmas": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Wisdom of Athena": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    "Wisdom of Athena 1000": GameConfig(0, "small", False, True, True, True, True, True, "PP"),
    # BNG
    "15 Dragon Pearls": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 African Drums": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Aztec Temples": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Carts of Gold": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Chillies and Joker: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 China Pots": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Clover Pots": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Clover Pots Extra": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Coin Volcanoes": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Coins": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Coins: Egypt": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Egypt Chests": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Fortune Trees": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Hot Chillies": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Hungry Pandas": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Luxor Pots: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Magic Lamps: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Pirate Barrels: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Pots Riches: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Pots Riches Extra: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Pots of Egypt": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "3 Super Hot Chillies: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "777 Coins": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "777 Fruity Classic": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "777 Gems Respin": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "African Spirit Sticky Wilds": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Amazonia Spirit": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Arizona Heist: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Aztec Fire - Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Aztec Fire 2 - Hold and Win Multi": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Aztec Sun": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Big Heist": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Black Wolf": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Black Wolf 2": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Bluffy Cat": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Book of Sun": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Book of Sun: Choice": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Book of Sun: Multichance": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Book of Wizard": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Book of Wizard: Crystal Chance": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Boom! Boom! Gold!": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Buddha Fortune": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Buffalo Power": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Buffalo Power 2: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Buffalo Power Megaways": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Caishen Wealth": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Candy Boom": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Cash Volcano": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "China Festival": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Clover Charm: Hit the Bonus": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Coin Lamp": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Coin Strike: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Coin Up: Hot Fire": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Coin Up: Lightning": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Coin Volcano - Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Crown and Diamonds: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Crystal Scarabs": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Dancing Joker": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Diamonds Power: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Dragon Pearls": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Dragon Wealth": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Dragon Wealth - Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Eggs of Gold": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Egypt Fire": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Energy Coins: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Energy Joker: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Eye of Gold": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fire Coins: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fire Temple: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fishin' Bear": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Flash Joker: Fever": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Forest Spirit": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fortune Globe": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fruits & Joker Fever": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fruits & Sevens: Fever": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Fruits Fever 5 Lines": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Goddess of Egypt": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Gold Express": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Gold Nuggets": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Golden Dancing Lion": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Golden Teapot": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Grab More Gold!": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Great Panda": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Green Chilli": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Green Chilli 2": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Happy Fish": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Hawaii Riches: Bonus Vault": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Hit More Gold": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Hit the Gold!": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Hot Chilli Joker": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Hot Fire Fruits": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Jingle Coins: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "King of the Sky: Hit the Bonus": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lady Fortune": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lamp of Wonder": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lava Coins": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Legend of Cleopatra Megaways": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lightning Clovers: Hit the Bonus": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lion Coins": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lion Gems: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Little Farm": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lord Fortune 2": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lotus Charm": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Lucky Penny": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Luxor Gold: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Magic Apple": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Magic Apple 2": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Magic Ball: Multichance": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Mammoth Peak: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Mariachi Lock": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Maya Sun": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Merry Giftmas: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Moon Sisters": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "More Magic Apple": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Nights of Fire": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Olaf Viking": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Olympian Gods": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Pearl Diver": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Pearl Diver 2: Treasure Chest": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Pearl Ocean: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Pig Up": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Piggy Power: Hit the Bonus": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Pink Joker: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Pirate Chest: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Power Crown: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Power Sun": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Queen of the Sun": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Rio Gems": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Rocket Wins": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Royal Coins 2: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Royal Express: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Royal Joker: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Scarab Boost": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Scarab Riches": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Scarab Temple": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sherwood Coins: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sky Coins": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sky Pearls": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Solar Queen": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Solar Temple": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sticky Piggy": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Storm of Olympus": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 2": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 3": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 4": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sunlight Princess": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Sunny Fruits 2: Hold and Win": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Super Hot Chilli": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    "Super Marble": GameConfig(0, "small", False, True, True, True, True, True, "BNG"),
    # JFF
    # "Fortune Gems (JFF)": GameConfig(0, "small", False, True, True, None, False, True, "JFF"),
    # "Fortune Gems 2 (JFF)": GameConfig(0, "small", False, True, True, None, False, True, "JFF"),
    # "Fortune Gems 3 (JFF)": GameConfig(0, "small", False, True, True, None, False, True, "JFF"),
    # R88
    "Color Game": GameConfig(6603, "small", False, True, True, None, False, True, "R88"),
    "Maya Gems": GameConfig(0, "small", False, True, True, None, False, True, "R88"),
    # Royal Slot Gaming
    "Fortune Gems 4": GameConfig(0, "small", False, True, True, None, False, False, "RSG"),
    "Super Ace 2": GameConfig(0, "small", False, True, True, None, False, True, "RSG"),
    # Yellow Bat
    "Atlantis": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Beasty Bingo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Bingo Bingo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Bingo Bonanza": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Boom Boom Marmot": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Crazy Color Gam": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Crazy Money": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Diamond Mines": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Drago Nova": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "DragoNova": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Dragon Gems": GameConfig(9157, "small", False, True, True, True, True, True, "YB"),
    "Dragon Gems Super Buy": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Dragon Gems Wheel": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "EZ Bingo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Fortune Treasure": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Gladiator Link TS": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Golden Aztec": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Golden Aztec Mega": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Heat Bingo": GameConfig(9167, "small", False, True, True, True, True, True, "YB"),
    "Joy Bingo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Light of Apollo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Lightning Bingo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Lucky Meow": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Magic Lamp Link TS": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Magical Alchemist": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Mermaid Sling": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Mermaid Slingo": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Money Bingo": GameConfig(9168, "small", False, True, True, True, True, True, "YB"),
    "Money Blast": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Open Sesame": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Pirate Legends": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Power Fortune": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Rolling 7": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Royal Ace": GameConfig(9135, "small", False, True, True, True, True, True, "YB"),
    "Royal Hunter": GameConfig(9140, "small", False, True, True, True, True, True, "YB"),
    "Super 30 Bingo": GameConfig(9163, "small", False, True, True, True, True, True, "YB"),
    "Sugar Crush": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Super Egypt": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Win Cai Shen": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    "Zhao Cai Pao": GameConfig(0, "small", False, True, True, True, True, True, "YB"),
    # Omni Play
    "Super Gems": GameConfig(0, "small", False, True, True, None, False, True, "OMNI"),
    "Super Gems 1000": GameConfig(0, "small", False, True, True, None, False, True, "OMNI"),
    "Super Gems Wheel": GameConfig(0, "small", False, True, True, None, False, True, "OMNI")
}

DEFAULT_GAME_CONFIG = GameConfig(0, "small", False, True, True, None, False, False, None)

USER_AGENTS = [
    # Windows Chrome
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/114.0.5735.91 Safari/537.36",
    # Mac Chrome
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) "
    "Version/16.1 Safari/605.1.15",
    # Mobile Android Chrome
    "Mozilla/5.0 (Linux; Android 11; Pixel 5) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/113.0.0.0 Mobile Safari/537.36",
    # iPhone Safari
    "Mozilla/5.0 (iPhone; CPU iPhone OS 15_3 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) "
    "Version/15.3 Mobile/15E148 Safari/604.1"
]

# === Screen Dimensions ===
SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size()
HALF_WIDTH = SCREEN_WIDTH // 2

# == Single Slot Size
SCREEN_POS = {
    "center_x": SCREEN_WIDTH // 2,
    "center_y": SCREEN_HEIGHT // 2,
    "right_x": SCREEN_WIDTH - 1,
    "bottom_y": SCREEN_HEIGHT - 1
}

# == Dual Slot Sizes
LEFT_SLOT_POS = {
    "center_x": HALF_WIDTH // 2,
    "center_y": SCREEN_HEIGHT // 2
}

RIGHT_SLOT_POS = {
    "center_x": HALF_WIDTH + (HALF_WIDTH // 2),
    "center_y": SCREEN_HEIGHT // 2
}


HOLD_DELAY_RANGE = (1.5, 3)  # Used with random.uniform(*HOLD_DELAY_RANGE)
# SPIN_DELAY_RANGE = (2.8, 3.5)  # Used with random.uniform(*SPIN_DELAY_RANGE)
SPIN_DELAY_RANGE = (1, 1.5)  # Used with random.uniform(*SPIN_DELAY_RANGE)
TIMEOUT_DELAY_RANGE = (0.5, 2.5)  # Used with random.uniform(*TIMEOUT_DELAY_RANGE)
EXECUTION_TIME_RANGE = (0.3, 0.45)
