#!/usr/bin/env python

import pyautogui
from collections import namedtuple

GameConfig = namedtuple("GameConfig", [
    "slot_size", "spin_btn", "auto_spin", "turbo", "feature",
    "auto_play_menu", "widescreen", "provider"
])

GAME_CONFIGS = {
    # Jili
    "10 Sparkling Crown": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Charge Buffalo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Coin Treasures": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Coin Treasures 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Coin Wild Horse": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 LUCKY LION": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Lucky Piggy": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Pot Dragons": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "3 Witch's Lamp": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "40 Sparkling Crown": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "7up7down": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Agent Ace": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Ali Baba": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Arena Fighter": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Aztec Priestess": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Baccarat": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bangla Beauty": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bao boon chin": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Big Small": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bikini Lady": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bingo Adventure": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bingo Carnaval": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bone Fortune": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bonus Hunter": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Book of Gold": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Boxing Extravaganza": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Boxing King": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Bubble Beauty": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Calaca Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Candy Baby": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Charge Buffalo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Charge Buffalo Ascent": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Chin Shi Huang": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Circus Joker 4096": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Clover Coins 3x3": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Coin Infinity Surge Reel": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Coin Tree": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crash Bonus": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crash Cricket": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crash Goal": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crash Touchdown": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crazy FaFaFa": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crazy Hunter": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crazy Hunter 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crazy Pusher": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Crazy777": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Cricket King 18": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Cricket Sah 75": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Dabanggg": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Devil Fire": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Devil Fire 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Diamond Party": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "DiamondParty": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Dragon Treasure": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Egypt's Glow": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Elf Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "European Roulette": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fa Fa Fa": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fengshen": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fish Prawn Crab": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Coins": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems 3": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Gems Scratch": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Monkey": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Pig": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fortune Tree": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "FortunePig": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Fruity Wheel": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Gem Party": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Go For Champion": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Go Goal Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "God Of Martial": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Gold Rush": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Bank": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Bank 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Empire": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Empire 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Joker": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Land": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Queen": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Temple": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Golden Treasure Lightning": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Happy Taxi": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Hawaii Beauty": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Hilo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Hot Chilli": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Hyper Burst": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Jili Caishen": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Jackpot Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Jackpot Joker": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Jhandi Munda": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Jogo Do Bicho": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Joker Coins": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Journey West M": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Jungle King": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Keno": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Keno Bonus Number": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Keno Super Chance": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "King Arthur": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Legacy of Egypt": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Lucky Ball": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Lucky Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Lucky Coming": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Lucky Doggy": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Lucky Goldbricks": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Lucky Jaguar": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Magic Lamp": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Magic Lamp Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Master Tiger": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Mayan Empire": GameConfig("small", False, True, True, None, False, True, "JILI"),
    # "Medusa": GameConfig("small", False, True, True, None, False, True, "JILI"), Conflict Key same name
    "Mega Ace": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Mines Gold": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Mines Grand": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Money Coming": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Money Coming 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Money Coming Expand Bets": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Money Pot": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Money Pot Deluxe": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Monkey Party": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Neko Fortune": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Night City": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Nightfall Hunting": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Number King": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Pappu": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Party Night": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Party Star": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Pharaoh Treasure": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Pirate Queen": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Pirate Queen 2": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Plinko": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Poker King": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Poseidon": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Potion Wizard": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Roma X Deluxe": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "RomaX": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Safari King": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Safari Mystery": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Samba": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Secret Treasure": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Seven Seven Seven": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "SevenSevenSeven": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Shanghai Beauty": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Shōgun": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Sic Bo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Sin City": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Speed Baccarat": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Super Ace": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Super Ace Deluxe": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Super Ace II": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Super Ace Joker": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Super Ace Scratch": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Super Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Super E-Sabong": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Super Rich": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Sweet Land": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Twin Wins": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "The Pig House": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Thor X": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Treasure Quest": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Trial of Phoenix": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Video Poker": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "War Of Dragons": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "West Hunger Bingo": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Wheel": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Wild Ace": GameConfig("small", False, True, True, None, False, False, "JILI"),
    "Wild Racer": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Win Drop": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Witches Night": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "World Cup": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Xi Yang Yang": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "XiYangYang": GameConfig("small", False, True, True, None, False, True, "JILI"),
    "Zeus": GameConfig("small", False, True, True, None, False, True, "JILI"),
    # Pocket Game Soft
    "Alchemy Gold": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Anubis Wrath": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Asgardian Rising": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Bakery Bonanza": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Bali Vacation": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Battleground Royale": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Bikini Paradise": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Buffalo Win": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Butterfly Blossom": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Caishen Wins": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Candy Bonanza": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Candy Burst": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Captain's Bounty": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Cash Mania": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Chicky Run": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Chocolate Deluxe": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Circus Delight": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Cocktail Nights": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Cruise Royale": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Crypto Gold": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dead Man's Riches": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Destiny of Sun & Moon": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Diner Delights": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Diner Frenzy Spins": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Doomsday Rampage": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Double Fortune": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dragon Hatch": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dragon Hatch 2": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dragon Legend": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dragon Tiger Luck": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dragon's Treasure Quest": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Dreams of Macau": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Egypt's Book of Mystery": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Emoji Riches": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Emperor's Favour": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Flirting Scholar": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Forge of Wealth": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Dragon": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Gods": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Mouse": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Ox": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Rabbit": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Snake": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fortune Tiger": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fruit Candy": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Fruity Candy": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Futebol Fever": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Galactic Gems": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Galaxy Miner": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ganesha Fortune": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ganesha Gold": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Garuda Gems": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Geisha's Revenge": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Gem Saviour": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Gem Saviour Conquest": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Gem Saviour Sword": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Gemstones Gold": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Genie's 3 Wishes": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Gladiator's Glory": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Graffiti Rush": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Grimms' Bounty: Hansel & Gretel": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Guardians of Ice and Fire": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Hawaiian Tiki": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Heist Stakes": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Heist of Stakes": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Hip Hop Panda": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Honey Trap of Diao Chan": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Hood vs Wolf": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Hotpot": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Incan Wonders": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Jack Frost's Winter": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Jack the Giant Hunter": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Jewels of Prosperity": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Journey to the Wealth": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Jungle Delight": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Jurassic Kingdom": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Knockout Riches": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Legend of Hou Yi": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Legend of Perseus": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Legendary Monkey King": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Leprechaun Riches": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Lucky Clover Lady": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Lucky Clover Riches": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Lucky Neko": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Lucky Piggy": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mafia Mayhem": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mahjong Ways": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mahjong Ways 2": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Majestic Treasures": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mask Carnival": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Medusa": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Medusa II": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mermaid Riches": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Midas Fortune": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mr. Hallow-Win": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mr. Treasure’s Fortune": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Muay Thai Champion": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Museum Mystery": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mystic Potion": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Mystical Spirits": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ninja Raccoon Frenzy": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ninja Racoon Frenzy": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ninja vs Samurai": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Oishi Delights": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Opera Dynasty": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Oriental Prosperity": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Phoenix Rises": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Piggy Gold": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Pinata Wins": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Plushie Frenzy": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Prosperity Fortune Tree": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Prosperity Lion": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Queen of Bounty": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Raider Jane's Crypt of Fortune": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Rave Party Fever": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Reel Love": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Rio Fantasia": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Rise of Apollo": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Rooster Rumble": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Safari Wilds": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Santa's Gift Rush": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Secret of Cleopatra": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Secrets of Cleopatra": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Shaolin Soccer": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Shark Bounty": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Songkran Splash": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Speed Winner": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Spirited Wonders": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Super Golf Drive": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Supermarket Spree": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Symbols of Egypt": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Thai River Wonders": GameConfig("small", False, True, True, None, False, False, "PG"),
    "The Great Icescape": GameConfig("small", False, True, True, None, False, False, "PG"),
    "The Queen's Banquet": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Three Crazy Piggies": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Totem Wonders": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Treasures of Aztec": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Tree of Fortune": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Tsar Treasures": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ultimate Striker": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Vampire's Charm": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ways of Qilin": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Ways of the Qilin": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Werewolf's Hunt": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Ape #3258": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Ape#3258": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Bandito": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Bounty Showdown": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Coaster": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Fireworks": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wild Heist Cashout": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Win Win Fish Prawn Crab": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Win Win Won": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Wings of Iguazu": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Yakuza Honor": GameConfig("small", False, True, True, None, False, False, "PG"),
    "Zombie Outbreak": GameConfig("small", False, True, True, None, False, False, "PG"),
    # Fa Chai
    "Animal Racing": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Boxing Riches": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Chilihuahua": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Chinese New Year": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Chinese New Year 2": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Cowboys": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Crazy Buffalo": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Chinese New Year Moreways": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Circus Dozer": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Da Le Men": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Egypt Bonanza": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Fortune Egg": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Fortune Koi": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Fortune Sheep": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Fa Chai Dozer": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Fortune Goddess": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Fortune Money Boom": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Glory of Rome": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Gold Rush": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Golden Genie": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Golden Panther": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Grand Blue": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Go Go Rise": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Gods Grant Fortune": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Happy Duo Bao": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Hot Pot Party": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Jungle Bang Bang": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Legend of Inca": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Lucky Fortunes": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Lucky Fortunes 3x3": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Luxury The Golden Panther": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Lightning Bomb": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Luxury Golden Panther": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Magic Beans": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Merge Magic": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Mines": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Money Tree Dozer": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Night Market": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Night Market 2": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Panda Dragon Boat": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Phoenix Fever": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Pong Pong Hu": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Poker Win": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Queen of Inca": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Rich Man": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Robin Hood": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Roma Gladiatrix": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Sugar Bang Bang 2": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Super Color Game": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Super Elements": GameConfig("small", True, True, True, None, False, False, "FC"),
    "The The Golden Panther": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Three Little Pigs": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Treasure Cruise": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Treasure Raiders": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Treasures of Odin": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Tower": GameConfig("small", True, True, True, None, False, False, "FC"),
    "War of the Universe": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Win Win Neko": GameConfig("small", True, True, True, None, False, False, "FC"),
    "Zeus": GameConfig("small", True, True, True, None, False, False, "FC"),
    # JDB
    "Aviator Extra Bet": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Banana Saga": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Beer Tycoon": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Big Three Dragons": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Birds and Animals": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Birds Party Deluxe": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Boom Fiesta": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Bull Treasure": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Cai Shen Bingo": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Cai Shen Party": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Caishen Coming": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Chef Panda": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Classic Mario": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Coo Coo Farm": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Crazy King Kong": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Dice": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Double Wilds": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Dragon Soar - Hyper Wild": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Dragon Warrior": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Dragon's Gate": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Egypt Treasure": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Firework Burst": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Fishin' Fever X-Huge": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Flirting Scholar Tang II": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Fortune Horse": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Fortune Jewel": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Fortune Neko": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Fortune Treasure": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Fruity Bonanza Combo": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Funky King Kong": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Galaxy Burst": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Glamorous Girl": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Go Lai Fu": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Goal": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Golden Disco": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Guan Gong": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Happy New Year": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "HiLo": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Horse Racing": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Huaguoshan Legends": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Jogo Do Bicho": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Jungle Jungle": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "King of Football": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Koi Trio": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lantern Wealth": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Legendary 5": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Llama Adventure": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lucky Color Game": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lucky Diamond": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lucky Dragon": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lucky Dragons": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lucky Qilin": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Lucky Racing": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Magic Ace Wild Lock": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Mahjong": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Maya Gold Crazy": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Miner Babe": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Mines": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Mines 2": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Mining Upstart": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Mjolnir": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Mole Crash": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Moneybags Man": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Napoleon": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Olympig": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "One Punch Man": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Orient Animals": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Panda Panda": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Pirate Treasure": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Plinko": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Pop Pop Candy 1000": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Prosperity Tiger": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Ragnarok: Thor vs Loki": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Rocket Derby": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Rolling in Money": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Rooster in Love": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Spindrift": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Spindrift 2": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Super Niubi Deluxe": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Super Super Fruit": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "The Llama Adventure": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Triple King Kong": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Wealthway": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Winning Mask": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Wonder Elephant": GameConfig("small", False, True, True, True, True, True, "JDB"),
    "Xi Yang Yang": GameConfig("small", False, True, True, True, True, True, "JDB"),
    # Pragmatic Play
    "3 Buzzing Wilds": GameConfig("small", False, True, True, True, True, True, "PP"),
    "3 Dancing Monkeys": GameConfig("small", False, True, True, True, True, True, "PP"),
    "3 Dancing Monkeys™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "5 Frozen Charms Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "5 Lions Dance": GameConfig("small", False, True, True, True, True, True, "PP"),
    "5 Rabbits Megaways™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "6 Jokers": GameConfig("small", False, True, True, True, True, True, "PP"),
    "7 Clovers of Fortune": GameConfig("small", False, True, True, True, True, True, "PP"),
    "7 Piggies": GameConfig("small", False, True, True, True, True, True, "PP"),
    "8 Golden Dragon Challenge": GameConfig("small", False, True, True, True, True, True, "PP"),
    "888 Bonanza™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "888 Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "African Elephant": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aladdin and the Sorcerer": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Angel vs Sinner": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Anime Mecha Megaways™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aztec Blaze™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aztec Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aztec Gems": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aztec Gems Deluxe": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aztec Powernudge": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Aztec Treasure Hunt": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Badge Blitz": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bali Dragon": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bandit Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Barn Festival": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Barnyard Megahays Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Beware The Deep Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Amazon Xtreme": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza - Keeping It Reel": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza - Reel Action": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Bonanza Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Christmas Bash": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Christmas Bash™ (Reel Kingdom Game)": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Crash": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Day at the Races": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Floats My Boat": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Halloween": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Hold & Spinner": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Hold & Spinner Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Mission Fishin'": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Secrets of the Golden Lake": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Splash": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Vegas Double Down Deluxe": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Bass Xmas Xtreme": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Big Juan": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bigger Bass Blizzard - Christmas Catch": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bigger Bass Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Black Bull": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Blade & Fangs": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Blazing Wilds Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bomb Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Book of Golden Sands": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Book of Tut Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bounty Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Bow of Artemis": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Buffalo King": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Buffalo King Untamed Megaways™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Caishen's Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Candy Blitz Bombs": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Candy Corner": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Candy Jar Cluster": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Candy Jar Clusters": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Candy Stars": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cash Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cash Box": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cash Box™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cash Chips": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cash Elevator": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Casino Heist Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Castle of Fire": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Chase for Glory": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cheeky Emperor™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Chests of Cai Shen": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Chicken Chase – Caccia alla Gallina": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Chicken Drop": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Chilli Heat Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Christmas Big Bass Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Christmas Carol Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cleocatra": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Clover Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Club Tropicana": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Coffee Wild™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Colossal Cash Zone": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Congo Cash": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Congo Cash XL": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cosmic Cash": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cowboy Coins": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cowboys Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Crank it Up": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Crown of Fire": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Crystal Caverns Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Curse of the Werewolf Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cyber Heist": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Cyclops Smash": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dance Party": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Day of Dead": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Demon Pots": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Demon Pots™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Devilicious": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Diamond Cascade": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Diamond Strike": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Diamonds of Egypt": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Ding Dong Christmas Bells": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Down the Rails": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dragon Gold 88": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dragon Hero": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dragon Hero™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dragon Hot Hold and Spin": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dragon Kingdom - Eyes of Fire": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dwarf & Dragon": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Dynamite Diggin Doug": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Egyptian Fortunes": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Elemental Gems Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Emerald King Rainbow Road": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Empty the Bank": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Excalibur Unleashed": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Extra Juicy Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Eye of Cleopatra": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Eye of the Storm": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fairytale Fortune": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fat Panda": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fiery Wild Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Archer": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Hot 100": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Hot 20": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Hot 40": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Hot 5": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Portals": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Strike": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fire Strike 2": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Firebird Spirit": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fish Eye": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fishin' Reels": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Floating Dragon": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Floating Dragon - Dragon Boat Festival": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Floating Dragon Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Floating Dragon New Year Festival Ultra Megaways Hold & Spin": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fortune Ace": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fortune Dragon": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fortune Hit'n Roll": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fortunes of Aztec": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Frogs & Bugs": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Frozen Tropics": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fruit Party": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fruit Party 2": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fruit Rainbow": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fruits of the Amazon": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fruity Treats": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Fury of Odin Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gates of Gatot Kaca": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gates of Olympus": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gates of Olympus 1000": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gems Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Genie 3 Wishes": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Genie Mega Reels": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Ghostbusters": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gladiator Legends": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Goblin Heist Powernudge": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gold Party": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gold Rush": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Gold Train": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Golden Dragon Inferno": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Golden Pig": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Golden Piggy Bank": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Golden Tiger": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Greek Gods": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Greedy Wolf": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Green Chilli": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Grizzly Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Guardians of The Monastery": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Guardians of the Void": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Himalayan Wild": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hercules & Pegasus": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Heroes Hunt": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot Fiesta": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot Pepper": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot Safari": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot to Burn": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot to Burn Extreme": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot to Burn Hold & Spin": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot to Burn Jackpot": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Hot Triple Sevens": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Irish Charms": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Irish Clover": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Irish Clover 100": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Irish Pot Luck": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Jasmine Dreams": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Joker King": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Jokers Jewels": GameConfig("small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Aztec Treasure": GameConfig("small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Book of Tut": GameConfig("small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Book of Tut Respin": GameConfig("small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Mayan Gods": GameConfig("small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Quest for Bermuda Riches": GameConfig("small", False, True, True, True, True, True, "PP"),
    "John Hunter and the Tomb of the Scarab Queen": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Joker’s Coins Hold & Win": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Kingdom of The Dead": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Knight Hot Spotz": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Kraken's Sky Bounty": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Legend of Heroes Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Legend of The Golden Monkey": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Little Gem": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Little Gem Hold & Spin": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Loch Ness Loot": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Lucky Dragons": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Lucky Grace and Charm": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Lucky Lightning": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Lucky, Grace & Charm Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Magic Journey": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mahjong Wins": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mahjong Wins 2": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Master Chen's Fortune": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Medusa Strike": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mega Don": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mega Wheel": GameConfig("small", False, True, True, True, True, True, "PP"),
    "MegaWheel™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mighty Kong": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mochimon": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Monster Superlanche": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Monkey Warrior": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Money Stacks": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mummyland Treasures": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mystery of the Orient": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Mystic Chief": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Nile Fortune": GameConfig("small", False, True, True, True, True, True, "PP"),
    "North Guardians": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Octobeer Fortunes": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Old Gold Miner Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Oodles of Noodles": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Panda Fortune 2": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Peak Power": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Penguins Christmas Party Time": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Phoenix Forge": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Piggy Bank Bills": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Piggy Bankers": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pinup Girls": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pirate Gold Deluxe": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pirate Golden Age": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pirates Pub": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pixie Wings": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pompeii Megareels Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pot of Fortune": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Power of Merlin Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Power of Ninja": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pub Kings": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pyramid Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Pyramid King": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Queen of Gods": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Queenie": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rabbit Garden": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rainbow Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rainbow Reels": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Reel Banks": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Release the Bison": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Release the Kraken": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Release the Kraken 2": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Release the Kraken Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Revenge of Loki Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Ripe Rewards": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rise of Giza Powernudge": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rise of Samurai 4": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Robber Strike": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rocket Blast Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Rujak Bonanza": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Running Sushi": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Saiyan Mania": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Samurai Code": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Santa": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Santa's Great Gifts": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Santa's Wonderland": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Santa’s Xmas Rush": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sea Fantasy": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Secret City Gold": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Shield of Sparta": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Shining Hot 100": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Shining Hot 20": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Shining Hot 40": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Shining Hot 5": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sky Bounty": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Smugglers Cove": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Snakes & Ladders - Snake Eyes": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Snakes and Ladders Megadice": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Spaceman": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Spartan King": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Spellbinding Mystery": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Spin & Score Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Spirit of Adventure": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Star Bounty": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Star Pirates Code": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Starlight Christmas": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Starlight Princess 1000": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Starlight Princess Pachi": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Starz Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Strawberry Cocktail": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Street Racer": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Striking Hot 5": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sugar Rush": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sugar Rush 1000": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sugar Rush™": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sumo Supreme Megaways": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Super Joker": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Super X": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Supermania": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sweet Bonanza 1000": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sweet Bonanza Xmas": GameConfig("small", False, True, True, True, True, True, "PP"),
    "Sweet Powernudge": GameConfig("small", False, True, True, True, True, True, "PP"),
    # BNG
    "15 Dragon Pearls": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 African Drums": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Aztec Temples": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Carts of Gold": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Chillies and Joker: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 China Pots": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Clover Pots": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Clover Pots Extra": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Coin Volcanoes": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Coins": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Coins: Egypt": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Egypt Chests": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Fortune Trees": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Hot Chillies": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Hungry Pandas": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Luxor Pots: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Magic Lamps: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Pirate Barrels: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Pots Riches: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Pots Riches Extra: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Pots of Egypt": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "3 Super Hot Chillies: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "777 Coins": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "777 Fruity Classic": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "777 Gems Respin": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "African Spirit Sticky Wilds": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Amazonia Spirit": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Arizona Heist: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Aztec Fire - Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Aztec Fire 2 - Hold and Win Multi": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Aztec Sun": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Big Heist": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Black Wolf": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Black Wolf 2": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Bluffy Cat": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Book of Sun": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Book of Sun: Choice": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Book of Sun: Multichance": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Book of Wizard": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Book of Wizard: Crystal Chance": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Boom! Boom! Gold!": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Buddha Fortune": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Buffalo Power": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Buffalo Power 2: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Buffalo Power Megaways": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Caishen Wealth": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Candy Boom": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Cash Volcano": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "China Festival": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Clover Charm: Hit the Bonus": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Coin Lamp": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Coin Strike: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Coin Up: Hot Fire": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Coin Up: Lightning": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Coin Volcano - Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Crown and Diamonds: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Crystal Scarabs": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Dancing Joker": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Diamonds Power: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Dragon Pearls": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Dragon Wealth": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Dragon Wealth - Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Eggs of Gold": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Egypt Fire": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Energy Coins: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Energy Joker: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Eye of Gold": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fire Coins: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fire Temple: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fishin' Bear": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Flash Joker: Fever": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Forest Spirit": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fortune Globe": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fruits & Joker Fever": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fruits & Sevens: Fever": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Fruits Fever 5 Lines": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Goddess of Egypt": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Gold Express": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Gold Nuggets": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Golden Dancing Lion": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Golden Teapot": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Grab More Gold!": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Great Panda": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Green Chilli": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Green Chilli 2": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Happy Fish": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Hawaii Riches: Bonus Vault": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Hit More Gold": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Hit the Gold!": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Hot Chilli Joker": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Hot Fire Fruits": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Jingle Coins: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "King of the Sky: Hit the Bonus": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lady Fortune": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lamp of Wonder": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lava Coins": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Legend of Cleopatra Megaways": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lightning Clovers: Hit the Bonus": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lion Coins": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lion Gems: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Little Farm": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lord Fortune 2": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lotus Charm": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Lucky Penny": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Luxor Gold: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Magic Apple": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Magic Apple 2": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Magic Ball: Multichance": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Mammoth Peak: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Mariachi Lock": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Maya Sun": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Merry Giftmas: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Moon Sisters": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "More Magic Apple": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Nights of Fire": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Olaf Viking": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Olympian Gods": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Pearl Diver": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Pearl Diver 2: Treasure Chest": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Pearl Ocean: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Pig Up": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Piggy Power: Hit the Bonus": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Pink Joker: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Pirate Chest: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Power Crown: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Power Sun": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Queen of the Sun": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Rio Gems": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Rocket Wins": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Royal Coins 2: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Royal Express: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Royal Joker: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Scarab Boost": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Scarab Riches": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Scarab Temple": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sherwood Coins: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sky Coins": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sky Pearls": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Solar Queen": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Solar Temple": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sticky Piggy": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Storm of Olympus": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 2": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 3": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sun of Egypt 4": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sunlight Princess": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Sunny Fruits 2: Hold and Win": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Super Hot Chilli": GameConfig("small", False, True, True, True, True, True, "BNG"),
    "Super Marble": GameConfig("small", False, True, True, True, True, True, "BNG"),
    # JFF
    # "Fortune Gems (JFF)": GameConfig("small", False, True, True, None, False, True, "JFF"),
    # "Fortune Gems 2 (JFF)": GameConfig("small", False, True, True, None, False, True, "JFF"),
    # "Fortune Gems 3 (JFF)": GameConfig("small", False, True, True, None, False, True, "JFF"),
    # R88
    "Maya Gems": GameConfig("small", False, True, True, None, False, True, "R88"),
    # Royal Slot Gaming
    "Fortune Gems 4": GameConfig("small", False, True, True, None, False, False, "RSG"),
    "Super Ace 2": GameConfig("small", False, True, True, None, False, True, "RSG"),
    # Yellow Bat
    "Atlantis": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Beasty Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Bingo Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Bingo Bonanza": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Boom Boom Marmot": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Crazy Color Gam": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Crazy Money": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Diamond Mines": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Drago Nova": GameConfig("small", False, True, True, True, True, True, "YB"),
    "DragoNova": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Dragon Gems": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Dragon Gems Super Buy": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Dragon Gems Wheel": GameConfig("small", False, True, True, True, True, True, "YB"),
    "EZ Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Fortune Treasure": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Gladiator Link TS": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Golden Aztec": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Golden Aztec Mega": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Heat Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Joy Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Light of Apollo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Lightning Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Lucky Meow": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Magic Lamp Link TS": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Magical Alchemist": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Mermaid Sling": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Mermaid Slingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Money Bingo": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Money Blast": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Open Sesame": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Pirate Legends": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Power Fortune": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Rolling 7": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Royal Ace": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Royal Hunter": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Sugar Crush": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Super Egypt": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Win Cai Shen": GameConfig("small", False, True, True, True, True, True, "YB"),
    "Zhao Cai Pao": GameConfig("small", False, True, True, True, True, True, "YB"),
}

DEFAULT_GAME_CONFIG = GameConfig("small", False, True, True, None, False, False, None)

USER_AGENTS = [
    # Windows Chrome
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/114.0.5735.91 Safari/537.36",
    # Mac Chrome
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) "
    "Version/16.1 Safari/605.1.15",
    # Mobile Android Chrome
    "Mozilla/5.0 (Linux; Android 11; Pixel 5) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/113.0.0.0 Mobile Safari/537.36",
    # iPhone Safari
    "Mozilla/5.0 (iPhone; CPU iPhone OS 15_3 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) "
    "Version/15.3 Mobile/15E148 Safari/604.1"
]

# === Screen Dimensions ===
SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size()
HALF_WIDTH = SCREEN_WIDTH // 2

# == Single Slot Size
SCREEN_POS = {
    "center_x": SCREEN_WIDTH // 2,
    "center_y": SCREEN_HEIGHT // 2,
    "right_x": SCREEN_WIDTH - 1,
    "bottom_y": SCREEN_HEIGHT - 1
}

# == Dual Slot Sizes
LEFT_SLOT_POS = {
    "center_x": HALF_WIDTH // 2,
    "center_y": SCREEN_HEIGHT // 2
}

RIGHT_SLOT_POS = {
    "center_x": HALF_WIDTH + (HALF_WIDTH // 2),
    "center_y": SCREEN_HEIGHT // 2
}


HOLD_DELAY_RANGE = (1.5, 3)  # Used with random.uniform(*HOLD_DELAY_RANGE)
# SPIN_DELAY_RANGE = (2.8, 3.5)  # Used with random.uniform(*SPIN_DELAY_RANGE)
SPIN_DELAY_RANGE = (1, 1.5)  # Used with random.uniform(*SPIN_DELAY_RANGE)
TIMEOUT_DELAY_RANGE = (0.5, 2.5)  # Used with random.uniform(*TIMEOUT_DELAY_RANGE)
EXECUTION_TIME_RANGE = (0.3, 0.45)
